[2021-05-16 19:46:53,567] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.create_table 2021-05-16T14:46:27.508410+00:00 [queued]>
[2021-05-16 19:46:53,578] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.create_table 2021-05-16T14:46:27.508410+00:00 [queued]>
[2021-05-16 19:46:53,578] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 19:46:53,578] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-05-16 19:46:53,578] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 19:46:53,609] {taskinstance.py:900} INFO - Executing <Task(BigQueryOperator): create_table> on 2021-05-16T14:46:27.508410+00:00
[2021-05-16 19:46:53,615] {standard_task_runner.py:53} INFO - Started process 13615 to run task
[2021-05-16 19:46:53,689] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: bigquery_data_load.create_table 2021-05-16T14:46:27.508410+00:00 [running]> alieymsxxn
[2021-05-16 19:46:53,699] {bigquery_operator.py:252} INFO - Executing: 
    SELECT * except(rank)
    FROM (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY vehicle_id ORDERED BY DATETIME(date, TIME(hpur, minute, 0))
            ) as rank
        FROM 'ma-airflow.analytics.history') as latest
    WHERE rank = 1;
    
[2021-05-16 19:46:57,511] {taskinstance.py:1145} ERROR - BigQuery job failed. Final error was: {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Expected ")" but got identifier "ORDERED" at [7:41]'}. The job was: {'kind': 'bigquery#job', 'etag': 'qi5bL0XbDF83p50OCO3HaA==', 'id': 'ma-airflow:asia-south1.job_pZUZkRC5n4nhbM7oFSnV0CNOT7ck', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/ma-airflow/jobs/job_pZUZkRC5n4nhbM7oFSnV0CNOT7ck?location=asia-south1', 'user_email': 'airflow@ma-airflow.iam.gserviceaccount.com', 'configuration': {'query': {'query': "\n    SELECT * except(rank)\n    FROM (\n        SELECT\n            *,\n            ROW_NUMBER() OVER (\n                PARTITION BY vehicle_id ORDERED BY DATETIME(date, TIME(hpur, minute, 0))\n            ) as rank\n        FROM 'ma-airflow.analytics.history') as latest\n    WHERE rank = 1;\n    ", 'destinationTable': {'projectId': 'ma-airflow', 'datasetId': 'analytics', 'tableId': 'latest'}, 'createDisposition': 'CREATE_IF_NEEDED', 'writeDisposition': 'WRITE_TRUNCATE', 'priority': 'INTERACTIVE', 'allowLargeResults': False, 'useLegacySql': False}, 'jobType': 'QUERY'}, 'jobReference': {'projectId': 'ma-airflow', 'jobId': 'job_pZUZkRC5n4nhbM7oFSnV0CNOT7ck', 'location': 'asia-south1'}, 'statistics': {'creationTime': '1621176416498', 'startTime': '1621176416578', 'endTime': '1621176416578'}, 'status': {'errorResult': {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Expected ")" but got identifier "ORDERED" at [7:41]'}, 'errors': [{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Expected ")" but got identifier "ORDERED" at [7:41]'}], 'state': 'DONE'}}
Traceback (most recent call last):
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/contrib/operators/bigquery_operator.py", line 279, in execute
    encryption_configuration=self.encryption_configuration
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 910, in run_query
    return self.run_with_configuration(configuration)
  File "/home/alieymsxxn/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 1344, in run_with_configuration
    format(job['status']['errorResult'], job))
Exception: BigQuery job failed. Final error was: {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Expected ")" but got identifier "ORDERED" at [7:41]'}. The job was: {'kind': 'bigquery#job', 'etag': 'qi5bL0XbDF83p50OCO3HaA==', 'id': 'ma-airflow:asia-south1.job_pZUZkRC5n4nhbM7oFSnV0CNOT7ck', 'selfLink': 'https://bigquery.googleapis.com/bigquery/v2/projects/ma-airflow/jobs/job_pZUZkRC5n4nhbM7oFSnV0CNOT7ck?location=asia-south1', 'user_email': 'airflow@ma-airflow.iam.gserviceaccount.com', 'configuration': {'query': {'query': "\n    SELECT * except(rank)\n    FROM (\n        SELECT\n            *,\n            ROW_NUMBER() OVER (\n                PARTITION BY vehicle_id ORDERED BY DATETIME(date, TIME(hpur, minute, 0))\n            ) as rank\n        FROM 'ma-airflow.analytics.history') as latest\n    WHERE rank = 1;\n    ", 'destinationTable': {'projectId': 'ma-airflow', 'datasetId': 'analytics', 'tableId': 'latest'}, 'createDisposition': 'CREATE_IF_NEEDED', 'writeDisposition': 'WRITE_TRUNCATE', 'priority': 'INTERACTIVE', 'allowLargeResults': False, 'useLegacySql': False}, 'jobType': 'QUERY'}, 'jobReference': {'projectId': 'ma-airflow', 'jobId': 'job_pZUZkRC5n4nhbM7oFSnV0CNOT7ck', 'location': 'asia-south1'}, 'statistics': {'creationTime': '1621176416498', 'startTime': '1621176416578', 'endTime': '1621176416578'}, 'status': {'errorResult': {'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Expected ")" but got identifier "ORDERED" at [7:41]'}, 'errors': [{'reason': 'invalidQuery', 'location': 'query', 'message': 'Syntax error: Expected ")" but got identifier "ORDERED" at [7:41]'}], 'state': 'DONE'}}
[2021-05-16 19:46:57,515] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=bigquery_data_load, task_id=create_table, execution_date=20210516T144627, start_date=20210516T144653, end_date=20210516T144657
[2021-05-16 19:47:03,522] {logging_mixin.py:112} INFO - [2021-05-16 19:47:03,521] {local_task_job.py:103} INFO - Task exited with return code 1
